<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title> Welcome To The Website Of Govt. Polytechnic Dwarahat,Almora</title>
	<link rel="stylesheet"href="style.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <script type="text/javascript">
  function kitun()
{
var a=document.getElementById("n").value;
if (a=="")
document.getElementById("n").style.border=" 2px solid red";
else
document.getElementById("n").style.border="";
}
function kitem()
{
var a=document.getElementById("e").value;
if (a=="")
document.getElementById("e").style.border=" 2px solid red";
else
document.getElementById("e").style.border="";
}
function kitmn()
{
var a=document.getElementById("m").value;
if (a=="")
document.getElementById("m").style.border=" 2px solid red";
else
document.getElementById("m").style.border="";
}
function kitsub()
{
var a=document.getElementById("s").value;
if (a=="")
document.getElementById("s").style.border=" 2px solid red";
else
document.getElementById("s").style.border="";
}
function kitcom()
{
var a=document.getElementById("c").value;
if (a=="")
document.getElementById("c").style.border=" 2px solid red";
else
document.getElementById("c").style.border="";
}
  </script>
</head>
<body>
<!----------------------------------------------------------NAVBAR 1------------------------------------------------------->
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="libary.php">Library |<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="staf.php">Faculty/Staff |</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" title="Uttarakhand Board of Technical Education"href="http://www.ubter.in/" target="_blank">UBTER |</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://uktech.ac.in/" title="Uttarakhand Technical University "target="_blank">UKTECH |</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.ugc.ac.in/" title="University Grants Commission"target="_blank">UGC |</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://mhrd.gov.in/" title="Ministry of Human Resource and Development"target="_blank">MHRD |</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="https://www.aicte-india.org/" title="All India Council for Technical Education"target="_blank">AICTE |</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Some Important
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="https://cmdashboard.uk.gov.in/" target="_blank">CM Helpline</a>
          <a class="dropdown-item" href="https://csr.uk.gov.in/" target="_blank">'Sahyoga'-CSR</a>
          
          <a class="dropdown-item" href="https://cmhelpline.uk.gov.in/" target="_blank">CM Monitoring Dashboard</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" title="National Programme on Technology Enhanced Learning"href="https://nptel.ac.in/" target="_blank">NPTEL |</a>
      </li>
    </ul>
  </div>
</nav>
<!----------------------------------------------------logo part------------------------------------------------>
<div class="container-fluid bg-light">
  <div class="row">
  <div class="col-lg-2 col-md-2 col-12">
    <center><img src="imgs/logo2.png"class="img-fluid"style="margin-top: 15px;"></center>
  </div>
  <div class="col-lg-10 col-md-10 col-12">
  <center><h1 style="color:RGB(0, 0, 128);">S.S.S.S.S.Ram Singh Bisht Government Polytechnic</h1>
  <h4 style="color:RGB(0, 0, 128);">Dwarahat (Almora),Uttrakhand</h4>
  <p style="color:RGB(0, 0,0);"> An institute of government of Uttrakhand</p></center>
  </div>
</div>
</div>
<!-------------------------------------------------------------------------NAV BAR ---------------------------------------->
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupported" aria-controls="navbarSupported" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<div class="collapse navbar-collapse" id="navbarSupported">
    <ul class="navbar-nav m-auto ">
      <li class="nav-item active">
        <a class="nav-link" href="index.php">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Campus
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="ghouse.php">Guest House</a>        
          <a class="dropdown-item" href="hostel.php">Hostel</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          College
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="histry.php">History</a>
          <a class="dropdown-item" href="mv.php">Mission & Vission</a>
          <a class="dropdown-item" href="pd.php">Principal's Disk</a>
          <a class="dropdown-item" href="ncc.php">NCC/NSS</a>

        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Academics
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="cse.php">Computer Science & Engineering</a>
          <a class="dropdown-item" href="elex.php">Electronics Engineering</a>
          <a class="dropdown-item" href="it.php">Information Technlogy</a>
          <a class="dropdown-item" href="civil.php">Civil Engineering</a>
          <a class="dropdown-item" href="pharmacy.php">Pharmacy</a>
         <a class="dropdown-item" href="momsp.php">MOM&SP</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" title="Training and Placement cell"href="tpcell.php">T&P Cell</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="community.php">Community</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" title="Right To Information"href="rti.php">RTI</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="contact.php">Contact Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="add.php">Addmission</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        About GPD
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="datile.php">Anti Ragging</a>
          <a class="dropdown-item" href="achive.php">Achievements</a>
          
          <a class="dropdown-item" href="gallary.php">Gallery</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://www.ubterex.in/Student/Login.aspx"> Check Result</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="nae.php">News & Event</a>
      </li>
    </ul>
  </div>
</nav>
<!--------------------------------------------------carousel part----------------------------------------------->
<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
    <li data-target="#demo" data-slide-to="3"></li>
    <li data-target="#demo" data-slide-to="4"></li>
    <li data-target="#demo" data-slide-to="5"></li>
    <li data-target="#demo" data-slide-to="6"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="imgs/cg2.jpeg"width="1100" height="500">
      <div class="carousel-caption">
        <h3>S.S.S.S.S. Ram Singh Bisht </h3>
        <p>Goverment Polytechnic Dwarahat</p>
      </div>   
    </div>
      <div class="carousel-item">
      <img src="imgs/3.gif" width="1100" height="500">
      <div class="carousel-caption">
      </div>   
    </div>
    <div class="carousel-item">
      <img src="imgs/c4.jpg"width="1100" height="500">
      <div class="carousel-caption">
        <h3>M.P.H. Hall</h3>
      </div>   
    </div>
    <div class="carousel-item">
      <img src="imgs/5.gif" width="1100" height="500">
      <div class="carousel-caption">
        <h3>CSE,IT AND PGDCA</h3>
        <p>Departmant</p>
      </div>   
    </div>
    <div class="carousel-item">
      <img src="imgs/6.jpg"width="1100" height="500">
      <div class="carousel-caption">
        <h3>Civil And Electronic Engineering</h3>
        <p>Departmant</p>
      </div>   
    </div>
    <div class="carousel-item">
      <img src="imgs/7.jpg"width="1100" height="500">
      <div class="carousel-caption">
      </div>   
    </div>
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
<!--------------------------------------------section part----------------------------------->
<div class="container-fluid my-4 py-6">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <div class="card" style="width:300px">
    <img class="card-img-top" src="imgs/b.jpg" alt="Card image" style="width:100%">
    <div class="card-body">
      <h4 class="card-title">Baby Rani Maurya</h4>
      <p class="card-text">Governer of Uttarakhand</p>
      <a href="https://en.wikipedia.org/wiki/Baby_Rani_Maurya" target="_blank" class="btn btn-primary stretched-link">See Profile</a>
    </div>
  </div>
</div>
<div class="col-lg-4 col-md-4 col-12">
  <div class="card" style="width:300px">
    <img class="card-img-top" src="imgs/cm3.jpeg" alt="Card image" style="width:100%; ">
    <div class="card-body">
      <h4 class="card-title">Pushkar Singh Dhami</h4>
      <p class="card-text">Chief Minister of Uttarakhand</p>
      <a href="https://en.wikipedia.org/wiki/Pushkar_Singh_Dhami" target="_blank" class="btn btn-primary stretched-link">See Profile</a>
    </div>
  </div>
</div>
<div class="col-lg-4 col-md-4 col-12">
  <div class="card" style="width:300px">
    <img class="card-img-top" src="imgs/prin.jpg" alt="Card image" style="width:100%">
    <div class="card-body">
      <h4 class="card-title">Mrs. Rachana Singh</h4>
      <p class="card-text">Principal of Govt. Polytechnic Dwarahat</p>
      <a href="prin.php" class="btn btn-primary stretched-link">See Profile</a>
    </div>
  </div>
</div>
</div>
</div>
<!-----------------------student important link part-------------------------------------------------->
 <h1>Student Important Links</h1>
 <hr class="bg-light mb-4 md-0 d-inline-block mx-auto"style=text-white "width: 35%;height:3px;">
 <div class="container-fluid my-4 py-6">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <div class="card" style="width:400px height: 500PX;">
    <div class="card-body">
      <h4 class="card-title">Online Addmission Form</h4>
      <a href="#" class="link " style="color:RGB(0, 0, 128);">Group E[Engineering Group]</a><br>
      <a href="#" class=" link " style="color:RGB(0, 0, 128);">Group P [Pharmacy]</a><br>
      <a href="#" class=" link " style="color:RGB(0, 0, 128);">M Group [MOMSP]</a><br>
    </div>
  </div>
</div>
<div class="col-lg-4 col-md-4 col-12">
  <div class="card" style="width:400px height: 500PX;">
    <div class="card-body">
      <h4 class="card-title">Download Result Winter/Summer </h4>
      <a href="#" class="link " style="color:RGB(0, 0, 128);">Group E[Engineering Group]</a><br>
      <a href="#" class="link " style="color:RGB(0, 0, 128);">Group P [Pharmacy]</a><br>
      <a href="#" class=" link " style="color:RGB(0, 0, 128);">M Group [MOMSP]</a><br>

    </div>
  </div>
</div>
<div class="col-lg-4 col-md-4 col-12">
  <div class="card" style="width:100px height: 500PX;">
    <div class="card-body">
      <h4 class="card-title"> Admit Card</h4>
      <a href="#" class="link " style="color:RGB(0, 0, 128);">Group E[Engineering Group]</a><br>
      <a href="#" class="link " style="color:RGB(0, 0, 128);">Group P [Pharmacy]</a><br>
      <a href="#" class=" link " style="color:RGB(0, 0, 128);">M Group [MOMSP]</a><br>
    </div>
  </div>
</div>
</div>
</div>
 <div class="container-fluid my-4 py-6">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <div class="card" style="width:400px height: 500PX;">
    <div class="card-body">
      <h4 class="card-title">Fee Details</h4>
      <a href="efee.php" class="link " style="color:RGB(0, 0, 128);">Group E[Engineering Group]</a><br>
      <a href="pfee.php" class="link " style="color:RGB(0, 0, 128);">Group P [Pharmacy]</a><br>
      <a href="momfee.php" class=" link " style="color:RGB(0, 0, 128);">M Group [MOMSP]</a><br>
    </div>
  </div>
</div>
<div class="col-lg-4 col-md-4 col-12">
  <div class="card" style="width:400px height: 500PX;">
    <div class="card-body">
      <h4 class="card-title">Student Feedback</h4>
      <a href="#" class="link " style="color:RGB(0, 0, 128);">Teaching</a><br>
      <a href="#" class="link " style="color:RGB(0, 0, 128);">Library</a><br>
      <a href="#" class=" link " style="color:RGB(0, 0, 128);">Administration</a><br>
    </div>
  </div>
</div>
<div class="col-lg-4 col-md-4 col-12">
  <div class="card" style="width:400px height: 500PX;">
    <div class="card-body">
      <h4 class="card-title">Examination Schedules</h4>
      <a href="#" class="link " style="color:RGB(0, 0, 128);">Group E[Engineering Group]</a><br>
      <a href="#" class="link " style="color:RGB(0, 0, 128);">Group P [Pharmacy]</a><br>
      <a href="#" class=" link " style="color:RGB(0, 0, 128);">M Group [MOMSP]</a><br>
    </div>
  </div>
</div>
</div>
</div>
<!------------------------------------------------------keep in tuch part------------------------------------>
<h1>Keep In Touch</h1>
<hr class="bg-dark mb-4 md-0 d-inline-block mx-auto"style="width: 20%;height:3px;">  
<div class="w-50 m-auto">
<form action="info.php" method="post">
<div class="form-group ">
  <label>Username</label>
<input type="text" name="name" id="n" onBlur="kitun()"placeholder="Plase Enter Your Name"autocomplete="off"class="form-control" required/>
</div>
<div class="form-group">
  <label>Email-ID</label>
<input type="email" name="email" onBlur="kitem()" id="e"placeholder="Plase Enter Your Email-ID"autocomplete="off"class="form-control"required/>
</div>
<div class="form-group">
  <label>Mobile Number</label>
<input type="number" name="mobile" onBlur="kitmn()"id="m"placeholder="Plase Enter Your Mobile Number"autocomplete="off"class="form-control"required/>
</div>
<div class="form-group">
  <label>Subject</label>
<input type="text" name="subject"id="s"onBlur="kitsub()" placeholder="Plase Enter Your Subject"autocomplete="off"class="form-control"required/>
</div>
<div class="form-group">
  <label>Comments</label>
<textarea class="form-control" onBlur="kitcom()"id="c"name="comments"placeholder="Comments"required/></textarea>
</div>
<button type="submit"class="btn btn-primary"> Submit</button>
</form>
</div>
<!--------------------------------------------------------Footer part------------------>
<footer class="page-footer bg-dark">
<div class="container text-center text-md-left mt-5">
<div class="row ">
<div class="col-lg-3 col-md-2 col-12 mx-auto mb-4 text-light">
<h6 class="font-weight-bold"style="color: white;"> G.P.DWARAHAT</h6>
<hr class="bg-light mb-4 md-0 d-inline-block mx-auto"style="width: 120px;height: 2px;"></hr>
<ul class="list-unstyled">
<li class="my-2"><i class="fas fa-map-marker-alt mr-2"></i>Address: Dwarahat,Almora,Uttarakhand</li>
<li class="my-2"><i class="fas fa-envelope mr-2"></i>Email: <a href="mailto:gpdwarahat@gmail.com" title="Email to GPDwarahat"target="_top" class="text-white text-decoration-none">gpdwarahat@gmail.com</a></li>
<li class="my-2"><i class="fab fa-chrome mr-2"></i>Website: <a href="gpdwarahat.in" title="website"target="_blank"class="text-white text-decoration-none">gpdwarahat.com</a></li>
<li class="my-2"><i class="fas fa-phone-volume mr-2"></i>Phone: <a href="tel:05966244227" title="phone"class="text-white text-decoration-none">05966-244227</a></li>
<li class="my-2"><i class="fas fa-fax mr-2"></i> Fax: <a href="tel:05966244208" title="Fax"class="text-white text-decoration-none">05966-244208</a></li>
</ul>
</div>
<div class="col-lg-2 col-md-2 col-12 mx-auto mb-4">
<h6 class="font-weight-bold"style="color: white;">QUICK ACCESS</h6>
<hr class="bg-light mb-4 md-0 d-inline-block mx-auto"style="width: 120px;height: 2px;">
<ul class="list-unstyled ">
<li class="my-2 text-white"><i class="far fa-hand-pointer mr-3"></i><a href="contact.php" class="text-white ">Contact</a></li>
<li class="my-2 text-white"><i class="far fa-hand-pointer mr-3"></i><a href="libary.php" class="text-white">Library</a></li>
<li class="my-2 text-white"><i class="far fa-hand-pointer mr-3"></i><a href="grices.php" class="text-white">Grievances</a></li>
<li class="my-2 text-white"><i class="far fa-hand-pointer mr-3"></i><a href="athletics.php" class="text-white">Athletics</a></li>
<li class="my-2 text-white"><i class="far fa-hand-pointer mr-3"></i><a href="calumni.php" class="text-white">Alumni</a></li>
<li class="my-2 text-white"><i class="far fa-hand-pointer mr-3"></i><a href="htr.php" class="text-white">How To Reach</a></li>
</ul>
</div>

<div class="col-lg-2 col-md-2 col-12 mx-auto mb-4">
<h6 class="font-weight-bold"style="color: white;">FOLLOW US</h6>
<hr class="bg-light mb-4 md-0 d-inline-block mx-auto"style="width: 110px;height: 2px;">
<ul class="list-unstyled ">
<li class="my-2"><i class="fab fa-facebook-square text-white mr-3"></i><a href="https://www.facebook.com/gpdwarahat/" target="_blank"class="text-white">Facebook</a></li>
<li class="my-2 text-white"><i class="fab fa-youtube text-white mr-3"></i><a href="https://www.university.youth4work.com/gpd_government-polytechnic-dwarahat" target="_blank" class="text-white">Youtube</a></li>
<li class="nav-item" style="margin-top: 40px;">
<button class="btn btn-success"><a class="text-white text-decoration-none"title="Only Admin Login"href="login.php">Adminlogin</a></button>
</li>
</ul>
</div>

<div class="col-lg-5 col-md-2 col-12 mx-auto mb-4">
<h6 class="font-weight-bold"style="color: white;">MAP</h6>
<hr class="bg-light mb-4 md-0 d-inline-block mx-auto"style="width: 60px;height: 2px;"></hr>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d432.9724900989144!2d79.42281613625039!3d29.755081900000537!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39a755626e856491%3A0x39ad931e10fdf92f!2z4KSX4KS14KSw4KWN4KSo4KSu4KWH4KSC4KSfIOCkquClieCksuCkv-Ckn-Clh-CkleCkqOCkv-CklSDgpJXgpYngpLLgpYfgpJwg4KSm4KWN4KS14KS-4KSw4KS-4KS54KS-4KSf!5e0!3m2!1shi!2sin!4v1609228323013!5m2!1shi!2sin" width="450" height="200" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</div>
<hr class="bg-light"style="width:100%;height:3px;"></hr>
</div>
</div>
</footer>
<div>
<h5 class="text-center bg-dark text-white ">Arjun Negi © 2021 | All Rights Reserved.</h5>
</div> 
 <!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>